import type { Metadata } from "next";
import "./globals.css";
import { ReactLenis } from "@/lib/lenis";
import { Toaster } from "@/components/ui/sonner";
import Preloader from "@/components/ui/Preloader";
import ScrollToTop from "@/components/layout/ScrollToTop";

export const metadata: Metadata = {
  title: "Home | CrevoSys",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <ReactLenis root>
        <body className={` antialiased`}>
          <Preloader />
          {children}
          <ScrollToTop />
          <Toaster />
        </body>
      </ReactLenis>
    </html>
  );
}
